template-file-path: templates/iam.yaml
parameters:
  EcrRepositoryArn: arn:aws:ecr:eu-west-1:714377355835:repository/spring-boot-app-repo
  GitHubBranch: main
  GitHubRepo: kaytee07/aws-java-webapp
tags: {}
