template-file-path: ecr.yaml
parameters:
  PrivateSubnet1Cidr: 10.0.2.0/24
  AllowedGithubRepo: kaytee07/aws-java-app
  PublicSubnet2Cidr: 10.0.1.0/24
  VpcCidr: 10.0.0.0/16
  EnvironmentName: taylor-ecs-stack
  PrivateSubnet2Cidr: 10.0.3.0/24
  AllowedGithubBranch: refs/heads/main
  AppPort: '80'
  PublicSubnet1Cidr: 10.0.0.0/24
tags: {}
