AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline and CodeDeploy for ECS blue/green

Parameters:
  PipelineName:
    Type: String
    Default: SpringBootPipeline
  EcrRepositoryName:
    Type: String
  CodePipelineRoleArn:
    Type: String
  CodeDeployRoleArn:
    Type: String
  EcsClusterName:
    Type: String
  EcsServiceName:
    Type: String
  BlueTargetGroupName:
    Type: String
    Description: Name of blue target group
  GreenTargetGroupName:
    Type: String
    Description: Name of green target group
  ListenerArn:
    Type: String
    Description: ARN of ALB listener

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-springboot-artifacts

  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: SpringBootCodeDeployApp
      ComputePlatform: ECS

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: SpringBootDeploymentGroup
      ServiceRoleArn: !Ref CodeDeployRoleArn
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - !Ref ListenerArn
            TargetGroups:
              - Name: !Ref BlueTargetGroupName
              - Name: !Ref GreenTargetGroupName
      ECSServices:
        - ServiceName: !Ref EcsServiceName
          ClusterName: !Ref EcsClusterName

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: ECRSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: '1'
              Configuration:
                RepositoryName: !Ref EcrRepositoryName
                ImageTag: latest
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: ECSDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              Configuration:
                ApplicationName: !Ref CodeDeployApp
                DeploymentGroupName: !Ref DeploymentGroup
              InputArtifacts:
                - Name: SourceOutput

Outputs:
  PipelineName:
    Value: !Ref CodePipeline
    Export:
      Name: !Sub ${AWS::StackName}-PipelineName